name: tester run
on:
  schedule:
    - cron: '0 */2 * * *'  # 
  workflow_dispatch:       # 

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout current repo
        uses: actions/checkout@v3

      - name: ğŸ Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ğŸ“¦ Install dependencies (if needed)
        run: |
          pip install --upgrade pip

      - name: ğŸš€ Run latency scanner script
        run: python tester.py

      - name: âœ… Commit and push updated results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.txt
          git commit -m " Auto update: Config latency sorted" || echo "No changes to commit"
          git push
        continue-on-error: true
